### ISSUE TITLE
[meta] Regarding the name of the package

### ISSUE THREAD

**Issue by papb** [djmitche/p-synchronize#1]
Hello @djmitche, I watch the [p-limit](https://github.com/sindresorhus/p-limit) repository and that's what brought me here. You've used the name `p-sync`, which caught my eye. I believe you probably won't be able to publish under this name, take a look at [this](https://github.com/Richienb/p-syncy/pull/1).

**Comment by djmitche** [comment]
Oh, that is a bit disappointing.  I suppose I could use `promise-sync`.  We'll see when I try to publish it.

**Comment by djmitche** [comment]
Thanks for the tip -- it's now https://classic.yarnpkg.com/en/package/p-synchronize
